# Generated by Django 5.2.8 on 2025-11-27 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('style', models.CharField(choices=[('no_style', 'No Style'), ('photo', 'Photo'), ('illustration', 'Illustration'), ('3d', '3D'), ('cartoon_fun', 'Cartoon Fun'), ('comic', 'Comic'), ('dark', 'Dark'), ('watercolor', 'Watercolor'), ('pixel_art', 'Pixel Art'), ('oil_painting', 'Oil Painting'), ('nature', 'Nature'), ('ink_print', 'Ink Print'), ('pencil', 'Pencil'), ('retrowave', 'Retrowave')], max_length=50)),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
